# Generated by Django 6.0 on 2025-12-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("financial", "Финансовый отчет"),
                            ("sales", "Отчет по продажам"),
                            ("inventory", "Складской отчет"),
                            ("performance", "Отчет по эффективности"),
                            ("customer", "Отчет по клиентам"),
                            ("technician", "Отчет по техникам"),
                        ],
                        max_length=20,
                        verbose_name="Тип отчета",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("config", models.JSONField(default=dict, verbose_name="Конфигурация")),
                (
                    "required_permissions",
                    models.JSONField(default=list, verbose_name="Необходимые права"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "available_for_roles",
                    models.ManyToManyField(
                        blank=True, to="users.role", verbose_name="Доступно для ролей"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("quarterly", "Ежеквартально"),
                        ],
                        max_length=20,
                        verbose_name="Частота",
                    ),
                ),
                (
                    "email_recipients",
                    models.TextField(blank=True, verbose_name="Email получатели"),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Параметры"),
                ),
                ("next_run", models.DateTimeField(verbose_name="Следующий запуск")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipients",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Получатели"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="Параметры"),
                ),
                ("date_from", models.DateTimeField(verbose_name="С даты")),
                ("date_to", models.DateTimeField(verbose_name="По дату")),
                ("data", models.JSONField(default=dict, verbose_name="Данные отчета")),
                ("summary", models.JSONField(default=dict, verbose_name="Сводка")),
                (
                    "charts_config",
                    models.JSONField(
                        default=dict, verbose_name="Конфигурация графиков"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь к файлу"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
    ]
