# Generated by Django 5.2.6 on 2025-09-16 08:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Принят"),
                            ("diagnosed", "Диагностирован"),
                            ("waiting_parts", "Ожидание запчастей"),
                            ("in_repair", "В ремонте"),
                            ("testing", "Тестирование"),
                            ("ready", "Готов к выдаче"),
                            ("completed", "Выдан"),
                            ("cancelled", "Отменен"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("normal", "Обычный"),
                            ("high", "Высокий"),
                            ("urgent", "Срочный"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(verbose_name="Описание проблемы"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Диагноз")),
                (
                    "work_description",
                    models.TextField(
                        blank=True, verbose_name="Описание выполненных работ"
                    ),
                ),
                (
                    "accessories",
                    models.TextField(blank=True, verbose_name="Комплектация"),
                ),
                (
                    "device_condition",
                    models.TextField(blank=True, verbose_name="Состояние устройства"),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Предварительная стоимость",
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Итоговая стоимость",
                    ),
                ),
                (
                    "prepayment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Предоплата",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "estimated_completion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Планируемая дата готовности",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Внутренние заметки"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за единицу"
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга в заказе",
                "verbose_name_plural": "Услуги в заказах",
                "db_table": "order_services",
            },
        ),
        migrations.CreateModel(
            name="AdditionalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("accessories", "Аксессуары"),
                            ("protection", "Защитные покрытия"),
                            ("software", "Программное обеспечение"),
                            ("cleaning", "Чистка"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shops",
                    models.ManyToManyField(
                        blank=True, to="shops.shop", verbose_name="Доступна в магазинах"
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительная услуга",
                "verbose_name_plural": "Дополнительные услуги",
                "db_table": "additional_services",
                "ordering": ["category", "name"],
            },
        ),
    ]
