# Generated by Django 5.2.6 on 2025-09-16 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0002_initial"),
        ("device", "0001_initial"),
        ("orders", "0001_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Назначен исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Принял заказ",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="customers.customer",
                verbose_name="Клиент",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="device.device",
                verbose_name="Устройство",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="shops.shop",
                verbose_name="Магазин",
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="orderservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.additionalservice",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="additional_services",
            field=models.ManyToManyField(
                blank=True,
                through="orders.OrderService",
                to="orders.additionalservice",
                verbose_name="Дополнительные услуги",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderservice",
            unique_together={("order", "service")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shop", "status"], name="orders_shop_id_30d977_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["customer"], name="orders_custome_6c3a7f_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_order_n_1336be_idx"
            ),
        ),
    ]
