# Generated by Django 6.0.4 on 2026-05-02 12:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderauditlog_orderstatushistory_repairstage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("updated", "Обновлен"),
                    ("status_changed", "Изменен статус"),
                    ("stage_added", "Добавлен этап"),
                    ("stage_updated", "Обновлен этап"),
                    ("approval_requested", "Запрошено согласование"),
                    ("approval_decided", "Решение по согласованию"),
                ],
                max_length=40,
                verbose_name="Действие",
            ),
        ),
        migrations.CreateModel(
            name="OrderApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Что согласовываем"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает решения"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "customer_comment",
                    models.TextField(blank=True, verbose_name="Комментарий клиента"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата решения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запроса"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_order_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто запросил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласование заказа",
                "verbose_name_plural": "Согласования заказов",
                "db_table": "order_approvals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "status"],
                        name="order_appro_order_i_6d56e4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="order_appro_created_5b1a3b_idx"
                    ),
                ],
            },
        ),
    ]
