# Generated by Codex on 2026-05-09

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models


def populate_existing_warranty(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    completed_orders = Order.objects.filter(
        status="completed",
        completed_at__isnull=False,
        warranty_until__isnull=True,
    )
    for order in completed_orders.iterator():
        Order.objects.filter(pk=order.pk).update(
            warranty_until=order.completed_at + timedelta(days=order.warranty_days)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_seed_quick_additional_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="warranty_days",
            field=models.PositiveIntegerField(
                default=90, verbose_name="Гарантия (дней)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="warranty_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Гарантия до"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_warranty_case",
            field=models.BooleanField(default=False, verbose_name="Гарантийный случай"),
        ),
        migrations.AddField(
            model_name="order",
            name="warranty_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warranty_cases",
                to="orders.order",
                verbose_name="Исходный заказ по гарантии",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="warranty_reason",
            field=models.TextField(
                blank=True, verbose_name="Причина гарантийного обращения"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="warranty_resolution",
            field=models.TextField(blank=True, verbose_name="Решение по гарантии"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_warranty_case", "status"],
                name="orders_is_warr_c99903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["warranty_parent"],
                name="orders_warrant_95238e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["warranty_until"],
                name="orders_warrant_dfe2fa_idx",
            ),
        ),
        migrations.RunPython(populate_existing_warranty, migrations.RunPython.noop),
    ]
