# Generated by Django 6.0.5 on 2026-05-09 18:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0007_order_warranty_flow"),
        ("shops", "0003_subscriptionplan_organizationsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Процент"),
                            ("fixed", "Фиксированная сумма"),
                        ],
                        default="percent",
                        max_length=20,
                        verbose_name="Тип скидки",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Размер скидки",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Максимальная скидка",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует с"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False, verbose_name="Применять автоматически"
                    ),
                ),
                (
                    "stackable",
                    models.BooleanField(
                        default=False, verbose_name="Можно сочетать с другими скидками"
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Общий лимит применений"
                    ),
                ),
                (
                    "per_customer_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Лимит на клиента"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_promotions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "shops",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Если филиалы не выбраны, акция доступна во всех филиалах.",
                        to="shops.shop",
                        verbose_name="Филиалы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
                "db_table": "promotions",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Промокод"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует с"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Общий лимит"
                    ),
                ),
                (
                    "per_customer_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Лимит на клиента"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="promotions.promotion",
                        verbose_name="Акция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
                "db_table": "promo_codes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Ручная скидка"),
                            ("promo_code", "Промокод"),
                            ("auto", "Автоматическая акция"),
                            ("loyalty", "Лояльность"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=160, verbose_name="Название скидки"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Сумма скидки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_order_discounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто применил",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="promotions.promocode",
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_discounts",
                        to="promotions.promotion",
                        verbose_name="Акция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка заказа",
                "verbose_name_plural": "Скидки заказов",
                "db_table": "order_discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_active", "auto_apply"], name="promotions_is_acti_2cac12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="promotions_starts__d30377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["is_active", "code"], name="promo_codes_is_acti_561c67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promocode",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="promo_codes_starts__c8eb99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdiscount",
            index=models.Index(
                fields=["order", "source"], name="order_disco_order_i_a51661_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdiscount",
            index=models.Index(
                fields=["promotion"], name="order_disco_promoti_d7a6b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderdiscount",
            index=models.Index(
                fields=["promo_code"], name="order_disco_promo_c_2a3840_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderdiscount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("promo_code__isnull", False)),
                fields=("order", "promo_code"),
                name="uniq_order_promo_code_discount",
            ),
        ),
    ]
