# Generated by Django 6.0.4 on 2026-05-03 18:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shops", "0003_subscriptionplan_organizationsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTypeStatsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                            ("custom", "Произвольный период"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("device_type_name", models.CharField(max_length=100)),
                ("orders", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снепшот по типам устройств",
                "verbose_name_plural": "Снепшоты по типам устройств",
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="analytics_d_period__f77a47_idx",
                    ),
                    models.Index(
                        fields=["shop"], name="analytics_d_shop_id_470dc5_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "period_type",
                        "period_start",
                        "period_end",
                        "shop",
                        "device_type_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="PopularServiceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                            ("custom", "Произвольный период"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("service_id", models.IntegerField()),
                ("service_name", models.CharField(max_length=200)),
                ("service_category", models.CharField(max_length=50)),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снепшот популярных услуг",
                "verbose_name_plural": "Снепшоты популярных услуг",
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="analytics_p_period__66079c_idx",
                    ),
                    models.Index(
                        fields=["shop"], name="analytics_p_shop_id_e5a26e_idx"
                    ),
                    models.Index(
                        fields=["revenue"], name="analytics_p_revenue_133895_idx"
                    ),
                ],
                "unique_together": {
                    ("period_type", "period_start", "period_end", "shop", "service_id")
                },
            },
        ),
        migrations.CreateModel(
            name="RevenueSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                            ("custom", "Произвольный период"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("orders", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "services_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снепшот выручки",
                "verbose_name_plural": "Снепшоты выручки",
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="analytics_r_period__e287ed_idx",
                    ),
                    models.Index(
                        fields=["shop", "period_type"],
                        name="analytics_r_shop_id_f02998_idx",
                    ),
                ],
                "unique_together": {
                    ("period_type", "period_start", "period_end", "shop")
                },
            },
        ),
        migrations.CreateModel(
            name="TechnicianPerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("day", "День"),
                            ("week", "Неделя"),
                            ("month", "Месяц"),
                            ("year", "Год"),
                            ("custom", "Произвольный период"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "avg_completion_days",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shop",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Снепшот эффективности техников",
                "verbose_name_plural": "Снепшоты эффективности техников",
                "indexes": [
                    models.Index(
                        fields=["period_type", "period_start"],
                        name="analytics_t_period__a998fd_idx",
                    ),
                    models.Index(
                        fields=["shop", "technician"],
                        name="analytics_t_shop_id_8c72ba_idx",
                    ),
                ],
                "unique_together": {
                    ("period_type", "period_start", "period_end", "shop", "technician")
                },
            },
        ),
    ]
