# Generated by Django 5.2.6 on 2025-09-16 08:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]+$", "Только заглавные буквы и цифры"
                            )
                        ],
                        verbose_name="Код магазина",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow",
                        max_length=50,
                        verbose_name="Часовой пояс",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Налоговая ставка (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
                "db_table": "shops",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number_prefix",
                    models.CharField(
                        default="ORD",
                        max_length=5,
                        verbose_name="Префикс номера заказа",
                    ),
                ),
                (
                    "auto_order_numbering",
                    models.BooleanField(
                        default=True, verbose_name="Автоматическая нумерация заказов"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS уведомления"),
                ),
                (
                    "email_notifications",
                    models.BooleanField(default=True, verbose_name="Email уведомления"),
                ),
                (
                    "work_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Начало работы"
                    ),
                ),
                (
                    "work_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Конец работы"
                    ),
                ),
                (
                    "work_days",
                    models.CharField(
                        default="1,2,3,4,5",
                        help_text="Номера дней недели через запятую (1=Пн, 7=Вс)",
                        max_length=20,
                        verbose_name="Рабочие дни",
                    ),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки магазина",
                "verbose_name_plural": "Настройки магазинов",
                "db_table": "shop_settings",
            },
        ),
    ]
