# Generated by Django 6.0 on 2025-12-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название юр. лица"),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=20, verbose_name="ИНН"),
                ),
                (
                    "kpp",
                    models.CharField(blank=True, max_length=20, verbose_name="КПП"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Юр. адрес"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "bank_details",
                    models.TextField(blank=True, verbose_name="Банковские реквизиты"),
                ),
                (
                    "website",
                    models.CharField(blank=True, max_length=200, verbose_name="Сайт"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="pos_barcode_enabled",
            field=models.BooleanField(default=False, verbose_name="POS с ШК включен"),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="receipt_footer_text",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Футер чека/квит."
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="work_days",
            field=models.CharField(
                default="1,2,3,4,5", max_length=20, verbose_name="Рабочие дни"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shops.organization",
                verbose_name="Организация",
            ),
        ),
    ]
