# Generated by Django 6.0.4 on 2026-05-02 12:56

import django.db.models.deletion
from django.db import migrations, models


def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("shops", "SubscriptionPlan")
    plans = [
        ("trial", "Бесплатный период 45 дней", "trial", 45, 0),
        ("monthly", "CRM на месяц", "month", 30, 1490),
        ("half_year", "CRM на полгода", "half_year", 182, 7990),
        ("yearly", "CRM на год", "year", 365, 14900),
    ]
    for code, name, period, days, price in plans:
        SubscriptionPlan.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "billing_period": period,
                "duration_days": days,
                "price": price,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0002_organization_shopsettings_pos_barcode_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("trial", "Пробный период"),
                            ("month", "Месяц"),
                            ("half_year", "Полгода"),
                            ("year", "Год"),
                        ],
                        max_length=20,
                        verbose_name="Период",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="Длительность, дней"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Тариф подписки",
                "verbose_name_plural": "Тарифы подписки",
                "db_table": "subscription_plans",
                "ordering": ["duration_days"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Пробный период"),
                            ("active", "Активна"),
                            ("expired", "Истекла"),
                            ("cancelled", "Отменена"),
                        ],
                        default="trial",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Дата начала")),
                ("expires_at", models.DateTimeField(verbose_name="Дата окончания")),
                (
                    "last_notice_bucket",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Последний bucket уведомления",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="shops.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="shops.subscriptionplan",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка организации",
                "verbose_name_plural": "Подписки организаций",
                "db_table": "organization_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="organizatio_status_62de1d_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="organizatio_expires_22c005_idx"
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_subscription_plans, migrations.RunPython.noop),
    ]
