# Generated by Django 6.0.5 on 2026-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0003_subscriptionplan_organizationsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Выезд мастера включён"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_service_name",
            field=models.CharField(
                default="Выезд мастера", max_length=100, verbose_name="Название услуги"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Базовая стоимость",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_out_of_zone_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Стоимость за пределами зон",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_description",
            field=models.TextField(blank=True, verbose_name="Описание услуги"),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_zones",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Зоны обслуживания"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="field_visit_advance_days",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Предварительная запись за (дней)"
            ),
        ),
    ]
