# Generated by Django 6.0.4 on 2026-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shops", "0006_shop_coordinates"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="default_goods_vat_code",
            field=models.CharField(
                choices=[
                    ("none", "Без НДС"),
                    ("vat0", "НДС 0%"),
                    ("vat5", "НДС 5%"),
                    ("vat7", "НДС 7%"),
                    ("vat10", "НДС 10%"),
                    ("vat20", "НДС 20%"),
                    ("vat22", "НДС 22%"),
                    ("vat105", "НДС 5/105"),
                    ("vat107", "НДС 7/107"),
                    ("vat110", "НДС 10/110"),
                    ("vat120", "НДС 20/120"),
                    ("vat122", "НДС 22/122"),
                ],
                default="none",
                max_length=20,
                verbose_name="НДС товаров по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="default_service_vat_code",
            field=models.CharField(
                choices=[
                    ("none", "Без НДС"),
                    ("vat0", "НДС 0%"),
                    ("vat5", "НДС 5%"),
                    ("vat7", "НДС 7%"),
                    ("vat10", "НДС 10%"),
                    ("vat20", "НДС 20%"),
                    ("vat22", "НДС 22%"),
                    ("vat105", "НДС 5/105"),
                    ("vat107", "НДС 7/107"),
                    ("vat110", "НДС 10/110"),
                    ("vat120", "НДС 20/120"),
                    ("vat122", "НДС 22/122"),
                ],
                default="none",
                max_length=20,
                verbose_name="НДС услуг по умолчанию",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fiscalization_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Фискализация включена"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="taxation_system",
            field=models.CharField(
                choices=[
                    ("osn", "ОСН"),
                    ("usn_income", "УСН доходы"),
                    ("usn_income_outcome", "УСН доходы-расходы"),
                    ("envd", "ЕНВД"),
                    ("esn", "ЕСХН"),
                    ("patent", "Патент"),
                ],
                default="usn_income",
                max_length=30,
                verbose_name="Система налогообложения",
            ),
        ),
    ]
