# Generated by Django 5.2.6 on 2025-09-16 08:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("website", "Сайт"),
                            ("social", "Социальные сети"),
                            ("referral", "Рекомендация"),
                            ("advertising", "Реклама"),
                            ("walk_in", "Зашел с улицы"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                        verbose_name="Откуда узнали",
                    ),
                ),
                (
                    "source_details",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Детали источника"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество заказов"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Общая сумма заказов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerShopHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_visit",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Первое посещение"
                    ),
                ),
                (
                    "last_visit",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее посещение"
                    ),
                ),
                (
                    "visits_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Количество посещений"
                    ),
                ),
            ],
            options={
                "verbose_name": "История клиента в магазине",
                "verbose_name_plural": "История клиентов в магазинах",
                "db_table": "customer_shop_history",
            },
        ),
    ]
