# Generated by Django 6.0 on 2025-12-22 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="marketing_consent",
            field=models.BooleanField(
                default=False, verbose_name="Согласие на коммуникации"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_channel",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("sms", "SMS")],
                max_length=10,
                verbose_name="Предпочтительный канал",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="customers_email_92e882_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_at"], name="customers_created_c63477_idx"
            ),
        ),
    ]
