# Generated by Django 6.0.5 on 2026-05-09 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_customer_portal_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="portal_is_active",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="portal_last_login_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="portal_password",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="portal_registered_at",
        ),
    ]
