# Generated by Django 6.0.4 on 2026-05-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shops", "0007_shopsettings_default_goods_vat_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Код источника"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Название")),
                (
                    "system_type",
                    models.CharField(blank=True, max_length=80, verbose_name="Тип CRM"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Источник импорта",
                "verbose_name_plural": "Источники импорта",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("validating", "Проверяется"),
                            ("ready", "Готов к импорту"),
                            ("importing", "Импортируется"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(default=True, verbose_name="Только проверка"),
                ),
                (
                    "options",
                    models.JSONField(blank=True, default=dict, verbose_name="Опции"),
                ),
                (
                    "counters",
                    models.JSONField(blank=True, default=dict, verbose_name="Счетчики"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shops.shop",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="data_import.migrationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет импорта",
                "verbose_name_plural": "Пакеты импорта",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExternalRecordLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=80, verbose_name="Тип сущности"),
                ),
                (
                    "external_id",
                    models.CharField(max_length=160, verbose_name="Внешний ID"),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Checksum"
                    ),
                ),
                (
                    "raw_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Снимок исходных данных"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_links",
                        to="data_import.importbatch",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_links",
                        to="data_import.migrationsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь внешней записи",
                "verbose_name_plural": "Связи внешних записей",
            },
        ),
        migrations.CreateModel(
            name="StagedImportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=80, verbose_name="Тип сущности"),
                ),
                (
                    "external_id",
                    models.CharField(max_length=160, verbose_name="Внешний ID"),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер строки"
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Исходные данные"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Checksum"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("valid", "Валиден"),
                            ("warning", "Есть предупреждения"),
                            ("error", "Ошибка"),
                            ("imported", "Импортирован"),
                            ("skipped", "Пропущен"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="data_import.importbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка импорта",
                "verbose_name_plural": "Строки импорта",
                "ordering": ["row_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImportIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Ошибка"),
                            ("warning", "Предупреждение"),
                            ("info", "Информация"),
                        ],
                        default="error",
                        max_length=20,
                        verbose_name="Важность",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Тип сущности"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Внешний ID"
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Номер строки"
                    ),
                ),
                (
                    "field_path",
                    models.CharField(blank=True, max_length=160, verbose_name="Поле"),
                ),
                ("code", models.CharField(max_length=80, verbose_name="Код")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Контекст"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="data_import.importbatch",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="data_import.stagedimportrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проблема импорта",
                "verbose_name_plural": "Проблемы импорта",
                "ordering": ["severity", "row_number", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["source", "status"], name="data_import_source__cc9025_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["shop", "created_at"], name="data_import_shop_id_d4eb22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalrecordlink",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="data_import_content_679784_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="externalrecordlink",
            index=models.Index(
                fields=["entity_type", "external_id"],
                name="data_import_entity__11b18f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="externalrecordlink",
            unique_together={("source", "entity_type", "external_id")},
        ),
        migrations.AddIndex(
            model_name="stagedimportrecord",
            index=models.Index(
                fields=["batch", "entity_type", "status"],
                name="data_import_batch_i_238cf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagedimportrecord",
            index=models.Index(
                fields=["entity_type", "external_id"],
                name="data_import_entity__d638bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importissue",
            index=models.Index(
                fields=["batch", "severity"], name="data_import_batch_i_2e3542_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importissue",
            index=models.Index(
                fields=["entity_type", "external_id"],
                name="data_import_entity__bc6514_idx",
            ),
        ),
    ]
