# Generated by Django 6.0 on 2025-12-22 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0003_customer_marketing_consent_and_more"),
        ("orders", "0002_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название программы"),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("points", "Бонусные баллы"),
                            ("cashback", "Кэшбэк"),
                            ("discount", "Скидочная программа"),
                        ],
                        default="points",
                        max_length=20,
                        verbose_name="Тип программы",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "earn_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Процент от суммы заказа",
                        max_digits=5,
                        verbose_name="Процент начисления",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "min_redeem_points",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Минимум баллов для списания"
                    ),
                ),
                (
                    "max_redeem_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Максимальный процент оплаты баллами",
                    ),
                ),
                (
                    "point_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        verbose_name="Стоимость одного балла (в рублях)",
                    ),
                ),
                (
                    "points_expire_days",
                    models.PositiveIntegerField(
                        blank=True,
                        default=365,
                        help_text="Оставьте пустым для бессрочных баллов",
                        null=True,
                        verbose_name="Срок действия баллов (дни)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shops",
                    models.ManyToManyField(
                        blank=True, to="shops.shop", verbose_name="Доступна в магазинах"
                    ),
                ),
            ],
            options={
                "verbose_name": "Программа лояльности",
                "verbose_name_plural": "Программы лояльности",
                "db_table": "loyalty_programs",
            },
        ),
        migrations.CreateModel(
            name="CustomerLoyalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(default=0, verbose_name="Всего баллов"),
                ),
                (
                    "available_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Доступно баллов"
                    ),
                ),
                (
                    "used_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Использовано баллов"
                    ),
                ),
                (
                    "tier_level",
                    models.CharField(
                        choices=[
                            ("bronze", "Бронзовый"),
                            ("silver", "Серебряный"),
                            ("gold", "Золотой"),
                            ("platinum", "Платиновый"),
                        ],
                        default="bronze",
                        max_length=20,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "tier_points_threshold",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Баллы для следующего уровня"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Общая сумма покупок",
                    ),
                ),
                (
                    "orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество заказов"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата вступления"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя активность"
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to="customers.customer",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие в программе лояльности",
                "verbose_name_plural": "Участие в программах лояльности",
                "db_table": "customer_loyalty",
                "unique_together": {("customer", "program")},
            },
        ),
        migrations.CreateModel(
            name="LoyaltyReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название награды"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("discount", "Скидка"),
                            ("free_service", "Бесплатная услуга"),
                            ("gift", "Подарок"),
                            ("points_bonus", "Бонусные баллы"),
                        ],
                        max_length=20,
                        verbose_name="Тип награды",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "required_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Необходимо баллов"
                    ),
                ),
                (
                    "required_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bronze", "Бронзовый"),
                            ("silver", "Серебряный"),
                            ("gold", "Золотой"),
                            ("platinum", "Платиновый"),
                        ],
                        max_length=20,
                        verbose_name="Необходимый уровень",
                    ),
                ),
                (
                    "required_orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Необходимо заказов"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Размер скидки (%)",
                    ),
                ),
                (
                    "bonus_points",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Бонусные баллы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует с"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Действует до"
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Оставьте пустым для безлимитного использования",
                        null=True,
                        verbose_name="Лимит использований",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда программы лояльности",
                "verbose_name_plural": "Награды программы лояльности",
                "db_table": "loyalty_rewards",
            },
        ),
        migrations.CreateModel(
            name="CustomerReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата использования"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использована"),
                ),
                (
                    "customer_loyalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="loyalty.customerloyalty",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Заказ, при котором была получена награда",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loyalty.loyaltyreward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Награда клиента",
                "verbose_name_plural": "Награды клиентов",
                "db_table": "customer_rewards",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PointsTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Начислено"),
                            ("redeemed", "Списано"),
                            ("expired", "Сгорели"),
                            ("bonus", "Бонус"),
                            ("refund", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                ("points", models.IntegerField(verbose_name="Количество баллов")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок действия"
                    ),
                ),
                (
                    "customer_loyalty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="loyalty.customerloyalty",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция баллов",
                "verbose_name_plural": "Транзакции баллов",
                "db_table": "points_transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
