# Generated by Django 6.0.4 on 2026-05-09 08:46

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        ("orders", "0006_seed_quick_additional_services"),
        ("shops", "0003_subscriptionplan_organizationsubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("yookassa", "ЮKassa")],
                        default="yookassa",
                        max_length=20,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("order", "Оплата заказа"),
                            ("subscription", "Оплата подписки"),
                        ],
                        max_length=20,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("waiting_for_capture", "Ожидает подтверждения"),
                            ("succeeded", "Оплачен"),
                            ("canceled", "Отменен"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        choices=[
                            ("any", "Платежная форма"),
                            ("bank_card", "Банковская карта"),
                            ("sbp", "СБП"),
                            ("yoo_money", "ЮMoney"),
                        ],
                        default="bank_card",
                        max_length=30,
                        verbose_name="Тип способа оплаты",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="ID платежа у провайдера",
                    ),
                ),
                (
                    "idempotence_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                (
                    "confirmation_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Ссылка на оплату"
                    ),
                ),
                (
                    "return_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Ссылка возврата"
                    ),
                ),
                (
                    "test_token",
                    models.UUIDField(
                        default=uuid.uuid4, verbose_name="Токен тестовой оплаты"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Данные провайдера"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "local_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payment",
                        to="finance.payment",
                        verbose_name="Локальный платеж",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="shops.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="shops.subscriptionplan",
                        verbose_name="Тариф подписки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Онлайн-платеж",
                "verbose_name_plural": "Онлайн-платежи",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purpose", "status"],
                        name="finance_onl_purpose_55afac_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_payment_id"],
                        name="finance_onl_provide_063c40_idx",
                    ),
                ],
            },
        ),
    ]
