# Generated by Django 6.0.4 on 2026-05-17 10:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def set_fiscal_payment_types(apps, schema_editor):
    PaymentMethod = apps.get_model("finance", "PaymentMethod")
    PaymentMethod.objects.filter(is_cash=True).update(fiscal_payment_type="cash")
    PaymentMethod.objects.filter(is_cash=False).update(fiscal_payment_type="electronic")


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_onlinepayment"),
        ("inventory", "0007_inventoryitem_fiscal_measure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onlinepayment",
            name="fiscal_receipt_error",
            field=models.TextField(blank=True, verbose_name="Ошибка подготовки чека"),
        ),
        migrations.AddField(
            model_name="onlinepayment",
            name="fiscal_receipt_snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Снимок фискального чека"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="fiscal_payment_mode",
            field=models.CharField(
                choices=[
                    ("full_prepayment", "Полная предоплата"),
                    ("partial_prepayment", "Частичная предоплата"),
                    ("advance", "Аванс"),
                    ("full_payment", "Полный расчет"),
                    ("partial_payment", "Частичный расчет и кредит"),
                    ("credit", "Передача в кредит"),
                    ("credit_payment", "Оплата кредита"),
                ],
                default="full_payment",
                max_length=30,
                verbose_name="Признак способа расчета",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="fiscal_required",
            field=models.BooleanField(
                default=True, verbose_name="Требуется фискальный чек"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="retail_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="inventory.retailsale",
                verbose_name="Розничная продажа",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="fiscal_payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("electronic", "Безналичные/электронные"),
                    ("prepaid", "Предварительная оплата"),
                    ("credit", "Постоплата/кредит"),
                    ("other", "Иная форма оплаты"),
                ],
                default="electronic",
                help_text="cash/electronic/prepaid/credit/other для ККМ и онлайн-чеков",
                max_length=20,
                verbose_name="Тип оплаты для фискального чека",
            ),
        ),
        migrations.RunPython(set_fiscal_payment_types, migrations.RunPython.noop),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("queued", "В очереди"),
                            ("sent", "Отправлен"),
                            ("registered", "Зарегистрирован"),
                            ("failed", "Ошибка"),
                            ("not_required", "Не требуется"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Провайдер ККМ"
                    ),
                ),
                (
                    "provider_receipt_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="ID чека у провайдера",
                    ),
                ),
                (
                    "taxation_system",
                    models.CharField(
                        choices=[
                            ("osn", "ОСН"),
                            ("usn_income", "УСН доходы"),
                            ("usn_income_outcome", "УСН доходы-расходы"),
                            ("envd", "ЕНВД"),
                            ("esn", "ЕСХН"),
                            ("patent", "Патент"),
                        ],
                        default="usn_income",
                        max_length=30,
                        verbose_name="Система налогообложения",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("electronic", "Безналичные/электронные"),
                            ("prepaid", "Предварительная оплата"),
                            ("credit", "Постоплата/кредит"),
                            ("other", "Иная форма оплаты"),
                        ],
                        default="electronic",
                        max_length=20,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма чека"
                    ),
                ),
                (
                    "received_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Получено текущим платежом",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="RUB", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email покупателя"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Телефон покупателя"
                    ),
                ),
                (
                    "normalized_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Нормализованный чек"
                    ),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Payload провайдера"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ответ провайдера"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_receipt",
                        to="finance.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фискальный чек",
                "verbose_name_plural": "Фискальные чеки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(verbose_name="Позиция")),
                (
                    "source_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Источник"
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID источника"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Наименование")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "vat_code",
                    models.CharField(
                        choices=[
                            ("none", "Без НДС"),
                            ("vat0", "НДС 0%"),
                            ("vat5", "НДС 5%"),
                            ("vat7", "НДС 7%"),
                            ("vat10", "НДС 10%"),
                            ("vat20", "НДС 20%"),
                            ("vat22", "НДС 22%"),
                            ("vat105", "НДС 5/105"),
                            ("vat107", "НДС 7/107"),
                            ("vat110", "НДС 10/110"),
                            ("vat120", "НДС 20/120"),
                            ("vat122", "НДС 22/122"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="НДС",
                    ),
                ),
                (
                    "payment_subject",
                    models.CharField(
                        choices=[
                            ("commodity", "Товар"),
                            ("service", "Услуга"),
                            ("work", "Работа"),
                            ("payment", "Платеж"),
                        ],
                        default="service",
                        max_length=30,
                        verbose_name="Признак предмета расчета",
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("full_prepayment", "Полная предоплата"),
                            ("partial_prepayment", "Частичная предоплата"),
                            ("advance", "Аванс"),
                            ("full_payment", "Полный расчет"),
                            ("partial_payment", "Частичный расчет и кредит"),
                            ("credit", "Передача в кредит"),
                            ("credit_payment", "Оплата кредита"),
                        ],
                        default="full_payment",
                        max_length=30,
                        verbose_name="Признак способа расчета",
                    ),
                ),
                (
                    "measure",
                    models.CharField(
                        choices=[
                            ("piece", "Штука"),
                            ("gram", "Грамм"),
                            ("kilogram", "Килограмм"),
                            ("ton", "Тонна"),
                            ("centimeter", "Сантиметр"),
                            ("decimeter", "Дециметр"),
                            ("meter", "Метр"),
                            ("square_meter", "Квадратный метр"),
                            ("liter", "Литр"),
                            ("day", "День"),
                            ("hour", "Час"),
                            ("service", "Услуга"),
                        ],
                        default="piece",
                        max_length=30,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Штрихкод"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Метаданные"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.paymentreceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция фискального чека",
                "verbose_name_plural": "Позиции фискальных чеков",
                "ordering": ["position"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["status", "created_at"], name="finance_pay_status_658431_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreceipt",
            index=models.Index(
                fields=["provider", "provider_receipt_id"],
                name="finance_pay_provide_ba2d60_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentreceiptitem",
            unique_together={("receipt", "position")},
        ),
    ]
