# Generated by Django 6.0 on 2025-12-22 11:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0002_initial"),
        ("shops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "sku",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Штрихкод"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("component", "Комплектующие"),
                            ("accessory", "Аксессуары"),
                            ("consumable", "Расходные материалы"),
                            ("tool", "Инструменты"),
                            ("software", "Программное обеспечение"),
                            ("service", "Услуга"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Технические характеристики",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Закупочная цена",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Продажная цена",
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="Наценка %",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="шт", max_length=20, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "track_quantity",
                    models.BooleanField(
                        default=True, verbose_name="Вести количественный учет"
                    ),
                ),
                (
                    "allow_negative_stock",
                    models.BooleanField(
                        default=False, verbose_name="Разрешить отрицательные остатки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "compatible_models",
                    models.ManyToManyField(
                        blank=True,
                        to="device.devicemodel",
                        verbose_name="Совместимые модели",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер заказа"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("confirmed", "Подтвержден"),
                            ("partially_received", "Частично получен"),
                            ("received", "Получен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "expected_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ожидаемая дата доставки"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактическая дата доставки"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Подитог",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Сумма налога",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Общая сумма",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="Условия"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shops.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ поставщику",
                "verbose_name_plural": "Заказы поставщикам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordered_quantity",
                    models.PositiveIntegerField(verbose_name="Заказано"),
                ),
                (
                    "received_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Получено"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за единицу"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Общая стоимость"
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул поставщика"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.purchaseorder",
                    ),
                ),
            ],
            options={
                "unique_together": {("purchase_order", "item")},
            },
        ),
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Зарезервировано"
                    ),
                ),
                (
                    "available_quantity",
                    models.IntegerField(default=0, verbose_name="Доступно"),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Минимальный остаток"
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Максимальный остаток"
                    ),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Точка перезаказа"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Место хранения"
                    ),
                ),
                (
                    "shelf",
                    models.CharField(blank=True, max_length=50, verbose_name="Полка"),
                ),
                (
                    "last_movement_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее движение"
                    ),
                ),
                (
                    "last_inventory_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя инвентаризация"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_balances",
                        to="inventory.inventoryitem",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shops.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остаток товара",
                "verbose_name_plural": "Остатки товаров",
                "unique_together": {("shop", "item")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Приход"),
                            ("shipment", "Расход"),
                            ("transfer", "Перемещение"),
                            ("adjustment", "Корректировка"),
                            ("reservation", "Резервирование"),
                            ("unreservation", "Снятие резерва"),
                            ("inventory", "Инвентаризация"),
                            ("write_off", "Списание"),
                            ("return", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                ("quantity_before", models.IntegerField(verbose_name="Количество до")),
                (
                    "quantity_change",
                    models.IntegerField(verbose_name="Изменение количества"),
                ),
                (
                    "quantity_after",
                    models.IntegerField(verbose_name="Количество после"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Себестоимость за единицу",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.purchaseorder",
                        verbose_name="Заказ поставщику",
                    ),
                ),
                (
                    "repair_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                        verbose_name="Заказ на ремонт",
                    ),
                ),
                (
                    "stock_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.stockbalance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение товара",
                "verbose_name_plural": "Движения товаров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Условия оплаты"
                    ),
                ),
                (
                    "delivery_terms",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Условия доставки"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Минимальная сумма заказа",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=3,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего заказов"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Общая сумма заказов",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул поставщика"
                    ),
                ),
                (
                    "supplier_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена поставщика"
                    ),
                ),
                (
                    "min_order_qty",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Минимальное количество заказа"
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Срок поставки (дни)"
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(default=False, verbose_name="Предпочтительный"),
                ),
                (
                    "last_order_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний заказ"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Part",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="primary_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_items",
                to="inventory.supplier",
                verbose_name="Основной поставщик",
            ),
        ),
        migrations.AddField(
            model_name="supplieritem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="supplieritem",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.supplier"
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                through="inventory.SupplierItem",
                to="inventory.supplier",
                verbose_name="Поставщики",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="supplieritem",
            unique_together={("supplier", "item")},
        ),
    ]
