# Generated by Django 6.0 on 2025-12-23 10:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_marketing_consent_and_more"),
        ("inventory", "0002_category_inventoryitem_purchaseorder_and_more"),
        ("shops", "0002_organization_shopsettings_pos_barcode_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sale_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер продажи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кассир",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="customers.customer",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shops.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розничная продажа",
                "verbose_name_plural": "Розничные продажи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarcodeScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50, verbose_name="Штрихкод")),
                (
                    "context",
                    models.CharField(
                        choices=[("pos", "Продажа (POS)"), ("inventory", "Склад")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Количество")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="shops.shop"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Скан ШК",
                "verbose_name_plural": "Сканы ШК",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["barcode"], name="inventory_b_barcode_8730c9_idx"
                    ),
                    models.Index(
                        fields=["shop", "context"],
                        name="inventory_b_shop_id_416085_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryItemBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50, verbose_name="Штрихкод")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "ШК товара",
                "verbose_name_plural": "ШК товаров",
                "indexes": [
                    models.Index(
                        fields=["barcode"], name="inventory_i_barcode_5c7433_idx"
                    )
                ],
                "unique_together": {("item", "barcode")},
            },
        ),
        migrations.CreateModel(
            name="InventoryItemCostHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ad_hoc", "Приемка без заказа"),
                            ("purchase_order", "Заказ поставщику"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.IntegerField(blank=True, null=True)),
                ("cost_per_unit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("quantity", models.IntegerField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_history",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shops.shop"
                    ),
                ),
            ],
            options={
                "verbose_name": "История себестоимости",
                "verbose_name_plural": "История себестоимости",
                "indexes": [
                    models.Index(
                        fields=["item", "received_at"],
                        name="inventory_i_item_id_97db25_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryItemPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[("purchase", "Закупочная"), ("selling", "Продажная")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "История цены",
                "verbose_name_plural": "История цен",
                "indexes": [
                    models.Index(
                        fields=["item", "price_type", "changed_at"],
                        name="inventory_i_item_id_9bd86a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RetailSaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.retailsale",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция продажи",
                "verbose_name_plural": "Позиции продажи",
                "unique_together": {("sale", "item")},
            },
        ),
    ]
