# Generated by Django 6.0.4 on 2026-05-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_inventoryproductgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequestbatch",
            name="purchase_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_request_batch",
                to="inventory.purchaseorder",
                verbose_name="Созданный заказ поставщику",
            ),
        ),
    ]
