# Generated by Django 6.0.4 on 2026-05-16 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_purchaserequestbatch_purchase_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequestAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("updated", "Обновлена"),
                            ("status_changed", "Изменен статус"),
                            ("split", "Разбита"),
                            ("batch_created", "Создан документ"),
                            ("order_created", "Создан заказ поставщику"),
                            ("received", "Принята поставка"),
                            ("pdf_downloaded", "Скачан PDF"),
                        ],
                        max_length=40,
                        verbose_name="Действие",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Описание")),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Изменения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_request_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="inventory.purchaserequestbatch",
                        verbose_name="Документ поставщику",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="inventory.purchaserequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита закупочной заявки",
                "verbose_name_plural": "Аудит закупочных заявок",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["purchase_request", "-created_at"],
                        name="inventory_p_purchas_57af06_idx",
                    ),
                    models.Index(
                        fields=["batch", "-created_at"],
                        name="inventory_p_batch_i_59cfaa_idx",
                    ),
                    models.Index(
                        fields=["action"], name="inventory_p_action_a539b9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestBatchStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("partially_received", "Частично получен"),
                            ("received", "Получен"),
                            ("cancelled", "Отменен"),
                        ],
                        max_length=32,
                        verbose_name="Старый статус",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("sent", "Отправлен"),
                            ("partially_received", "Частично получен"),
                            ("received", "Получен"),
                            ("cancelled", "Отменен"),
                        ],
                        max_length=32,
                        verbose_name="Новый статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="inventory.purchaserequestbatch",
                        verbose_name="Документ поставщику",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_request_batch_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса документа заявки",
                "verbose_name_plural": "История статусов документов заявок",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "-changed_at"],
                        name="inventory_p_batch_i_d11991_idx",
                    ),
                    models.Index(
                        fields=["new_status"], name="inventory_p_new_sta_327281_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Ожидает проверки"),
                            ("approved", "Согласована"),
                            ("split", "Разбита"),
                            ("sent", "Отправлена поставщику"),
                            ("partially_received", "Частично получена"),
                            ("received", "Закрыта"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена"),
                        ],
                        max_length=32,
                        verbose_name="Старый статус",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Ожидает проверки"),
                            ("approved", "Согласована"),
                            ("split", "Разбита"),
                            ("sent", "Отправлена поставщику"),
                            ("partially_received", "Частично получена"),
                            ("received", "Закрыта"),
                            ("rejected", "Отклонена"),
                            ("cancelled", "Отменена"),
                        ],
                        max_length=32,
                        verbose_name="Новый статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_request_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="inventory.purchaserequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "История статуса заявки",
                "verbose_name_plural": "История статусов заявок",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["purchase_request", "-changed_at"],
                        name="inventory_p_purchas_6faf31_idx",
                    ),
                    models.Index(
                        fields=["new_status"], name="inventory_p_new_sta_ed56dd_idx"
                    ),
                ],
            },
        ),
    ]
