# Generated by Django 6.0.4 on 2026-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_purchaserequestauditlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="fiscal_measure",
            field=models.CharField(
                choices=[
                    ("piece", "Штука"),
                    ("gram", "Грамм"),
                    ("kilogram", "Килограмм"),
                    ("ton", "Тонна"),
                    ("centimeter", "Сантиметр"),
                    ("decimeter", "Дециметр"),
                    ("meter", "Метр"),
                    ("square_meter", "Квадратный метр"),
                    ("liter", "Литр"),
                    ("day", "День"),
                    ("hour", "Час"),
                    ("service", "Услуга"),
                ],
                default="piece",
                max_length=30,
                verbose_name="Единица измерения для ККМ",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="fiscal_subject",
            field=models.CharField(
                choices=[
                    ("commodity", "Товар"),
                    ("service", "Услуга"),
                    ("work", "Работа"),
                    ("payment", "Платеж"),
                ],
                default="commodity",
                max_length=30,
                verbose_name="Фискальный предмет расчета",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="fiscal_vat_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "Без НДС"),
                    ("vat0", "НДС 0%"),
                    ("vat5", "НДС 5%"),
                    ("vat7", "НДС 7%"),
                    ("vat10", "НДС 10%"),
                    ("vat20", "НДС 20%"),
                    ("vat22", "НДС 22%"),
                    ("vat105", "НДС 5/105"),
                    ("vat107", "НДС 7/107"),
                    ("vat110", "НДС 10/110"),
                    ("vat120", "НДС 20/120"),
                    ("vat122", "НДС 22/122"),
                ],
                default="",
                help_text="Если пусто, используется НДС товаров из настроек филиала",
                max_length=20,
                verbose_name="НДС для фискального чека",
            ),
        ),
    ]
