# Generated by Django 5.2.6 on 2025-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Квитанция"),
                            ("warranty", "Гарантийный талон"),
                            ("invoice", "Счет"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
