# Generated by Django 6.0 on 2025-12-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("retail_receipt", "Чек (термолента)"),
                            ("retail_invoice", "Квитанция/накладная (A4)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/retail/")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Документ продажи",
                "verbose_name_plural": "Документы продажи",
                "ordering": ["-generated_at"],
            },
        ),
    ]
