# Generated by Django 6.0 on 2025-12-23 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_retaildocument"),
        ("inventory", "0003_retailsale_barcodescanevent_inventoryitembarcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retaildocument",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.retailsale"
            ),
        ),
    ]
