# Generated by Django 6.0.5 on 2026-05-09 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0007_order_warranty_flow"),
        ("shops", "0003_subscriptionplan_organizationsubscription"),
        ("tasks", "0002_task_kind_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortalIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, verbose_name="Клиентская часть включена"
                    ),
                ),
                (
                    "base_url",
                    models.URLField(blank=True, verbose_name="URL клиентского backend"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sync API ключ"
                    ),
                ),
                (
                    "tenant_key",
                    models.CharField(
                        blank=True,
                        help_text="Стабильный код компании во внешнем клиентском backend",
                        max_length=80,
                        verbose_name="Ключ tenant/company",
                    ),
                ),
                (
                    "client_domain",
                    models.URLField(
                        blank=True, verbose_name="Домен клиентского кабинета"
                    ),
                ),
                (
                    "auth_policy",
                    models.CharField(
                        choices=[
                            ("phone_or_email", "Телефон или email"),
                            ("phone_only", "Только телефон"),
                            ("email_only", "Только email"),
                        ],
                        default="phone_or_email",
                        max_length=20,
                        verbose_name="Политика входа клиентов",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Телефон поддержки"
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email поддержки"
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название бренда"
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Акцентный цвет"
                    ),
                ),
                (
                    "last_push_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний push заказов"
                    ),
                ),
                (
                    "last_pull_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний pull действий"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_portal_integration",
                        to="shops.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интеграция клиентского кабинета",
                "verbose_name_plural": "Интеграции клиентских кабинетов",
                "db_table": "client_portal_integrations",
            },
        ),
        migrations.CreateModel(
            name="ClientSyncAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=120, verbose_name="ID действия во внешнем кабинете"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(max_length=80, verbose_name="Тип действия"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="Payload"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("applied", "Применено"),
                            ("rejected", "Отклонено"),
                            ("error", "Ошибка"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Применено"
                    ),
                ),
                (
                    "synced_back_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ответ отправлен в кабинет"
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="client_sync.clientportalintegration",
                        verbose_name="Интеграция",
                    ),
                ),
                (
                    "related_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sync_actions",
                        to="orders.order",
                        verbose_name="Связанный заказ",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_sync_actions",
                        to="tasks.task",
                        verbose_name="Связанная задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие клиентского кабинета",
                "verbose_name_plural": "Действия клиентского кабинета",
                "db_table": "client_sync_actions",
            },
        ),
        migrations.CreateModel(
            name="ClientSyncOrderState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "remote_order_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="ID заказа в кабинете"
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Hash последнего снимка"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("synced", "Синхронизирован"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Попытки"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последняя успешная синхронизация",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_states",
                        to="client_sync.clientportalintegration",
                        verbose_name="Интеграция",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_sync_states",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состояние синхронизации заказа",
                "verbose_name_plural": "Состояния синхронизации заказов",
                "db_table": "client_sync_order_states",
            },
        ),
        migrations.AddIndex(
            model_name="clientportalintegration",
            index=models.Index(
                fields=["enabled"], name="client_port_enabled_10fd6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientportalintegration",
            index=models.Index(
                fields=["tenant_key"], name="client_port_tenant__b1f7ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncaction",
            index=models.Index(
                fields=["integration", "status"], name="client_sync_integra_7daae6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncaction",
            index=models.Index(
                fields=["action_type"], name="client_sync_action__438c84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncaction",
            index=models.Index(
                fields=["related_order"], name="client_sync_related_1f1a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncaction",
            index=models.Index(
                fields=["received_at"], name="client_sync_receive_4b6405_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientsyncaction",
            constraint=models.UniqueConstraint(
                fields=("integration", "external_id"), name="uniq_client_sync_action"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncorderstate",
            index=models.Index(
                fields=["integration", "status"], name="client_sync_integra_b81ca3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientsyncorderstate",
            index=models.Index(fields=["order"], name="client_sync_order_i_cbfde9_idx"),
        ),
        migrations.AddIndex(
            model_name="clientsyncorderstate",
            index=models.Index(
                fields=["last_synced_at"], name="client_sync_last_sy_f03541_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientsyncorderstate",
            constraint=models.UniqueConstraint(
                fields=("integration", "order"), name="uniq_client_sync_order_state"
            ),
        ),
    ]
