# Generated by Django 6.0.4 on 2026-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminServiceState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=40, unique=True),
                ),
                ("subscription", models.JSONField(blank=True, default=dict)),
                ("campaigns", models.JSONField(blank=True, default=list)),
                ("support_unread", models.PositiveIntegerField(default=0)),
                ("server_time", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_message", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Состояние RepireCRM Admin",
                "verbose_name_plural": "Состояния RepireCRM Admin",
                "db_table": "admin_service_state",
            },
        ),
    ]
