# Generated by Django 6.0.5 on 2026-05-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_profile_compensation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="category",
            field=models.CharField(
                choices=[
                    ("orders", "Заказы"),
                    ("customers", "Клиенты"),
                    ("inventory", "Склад"),
                    ("reports", "Отчеты"),
                    ("tasks", "Задачи"),
                    ("finance", "Финансы"),
                    ("marketing", "Маркетинг"),
                    ("settings", "Настройки"),
                    ("users", "Пользователи"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
