# Generated by Django 6.0.5 on 2026-05-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_permission_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_field_visit",
            field=models.BooleanField(default=False, verbose_name="Может выезжать"),
        ),
    ]
